name: Terraform Plan and Apply

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**/*.tf"

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Apply Terraform Changes
    runs-on: ubuntu-latest

    env:
      TERRAFORM_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
      ARM_CLIENT_ID: ${{ secrets.TF_API_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.TF_API_TENANT_ID }}
      ARM_USE_OIDC: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Write Terraform Cloud credentials
        run: |
          mkdir -p ~/.terraform.d
          echo "{\"credentials\": {\"app.terraform.io\": {\"token\": \"${TERRAFORM_CLOUD_TOKEN}\"}}}" > ~/.terraform.d/credentials.tfrc.json

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve
